# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/code_notes/',
                'doc_host': 'https://muellerzr.github.io',
                'git_url': 'https://github.com/muellerzr/muellerzr/code-notes/',
                'lib_path': 'code_notes'},
  'syms': {}}